### ISSUE TITLE
CSP Headers only being injected when Enable Rule Collection is disabled

### ISSUE THREAD

**Issue by fishouttah20** [david-risney/CSP-Fiddler-Extension#10]
This is a fresh install of Fiddler 4.5.1.2 on a Windows 7 system. I used the powershell command to pull the DLL today. I'm using Firefox 39.

CSP Headers are only being injected when the Enable Rule Collection on the CSP Rule Collector tab is UNCHECKED. This means I see the CSP errors in the Firefox Developer console only when Rule Collection is disabled. Enabled, there are no errors as no CSP header is being added.

Because Rule Collection is disabled, the URI is never added on the Rule Collector tab.

I found that if I Disabled rule collection, went to Firefox, Began loading a complex page, switched back to Fiddler and enabled Rule Collection, the Extension would capture the CSP error reports and generate a CSP for the traffic that was loaded after I clicked Enable Rule Collection. This of course only creates a partial rule, and attempting to browse to another page with Rule Collection Enabled means new CSP headers are not created for subsequent content.

Is this a bug in the extension? A change to Fiddler? 

I repeated this on a Windows 10 system with the same results

**Comment by david-risney** [comment]
I also see this bug with Fiddler4 when running latest Chrome and Firefox. I'm not sure what has changed to have this bug show up. I'll debug.

**Comment by david-risney** [comment]
Looks like it was caused by a bad merge. Not sure how I missed this. Thanks for opening!

**Comment by fishouttah20** [comment]
Thanks for fixing, it works much better now :) Great plugin btw, incredibly useful! Thanks!
